### ISSUE TITLE
Crash on 0.3.1.0

### ISSUE THREAD

**Issue by Czupak** [Timberborn-Modding-Central/TimberAPI#40] opened 2022-11-22 18:08 UTC
Any plans on updating to the newest version from experimental branch 0.3.1.0-4526a87-xgw? Do you prepare such releases or wait for game version hit the "production"?

(btw: isn't that weird for early access game to have an experimental branch? ;) )

![image](https://user-images.githubusercontent.com/10432092/203388403-bef62b02-21f3-4746-8f66-9d126f9dfadb.png)

**Comment by hytonhan** [comment] 2022-11-23 08:11
Hello! Currently we are not planning on supporting the experimental branch. Last time we did that it caused a lot of confusion with the users when the latest version worked only on experimental, and people on the stable downloaded it and it didn't work for them. To save us the trouble, we are at the very least waiting for some time before supporting experimental. 

The problem is that there are no easy ways to support both stable and experimental, which is a bit sad. That's why we have chosen to support mainly the stable.

**Comment by KYPremco** [comment] 2022-11-24 22:44
TimberAPI has been fixed in this PR: https://github.com/Timberborn-Modding-Central/TimberAPI/pull/41/

If you want to use it you can build and play with it.

**Closed by KYPremco** 2022-11-24 22:44 UTC

**Comment by Czupak** [comment] 2022-11-25 05:18
Thanks @hytonhan, that makes lot of sense.

Thanks @KYPremco, I'll check it out :)
